### ISSUE TITLE
Jobs__c.Parameters__c missing from master HEAD

### ISSUE THREAD

**Issue by emfournier** [zachelrath/Relax#12]
1.  classes/BatchAccountsUpdater.cls -- Error: Dependent class is invalid and needs recompilation:
   Class.BatchableProcessStep: line 1, column 52
   SimpleProcessStep: line 15, column 12: Invalid field Parameters__c for SObject Job__c (line 1, column 43)

...etc. blah blah for every reference

Of course it's there in the package :-) Thanks! --Eric (emf@umn.edu)

**Comment by zachelrath** [comment]
True that, will fix :+1:

**Comment by zachelrath** [comment]
Closed with commit 6d638dbf8e3468b5bc58f9230a2206cde00d5a5c
