### ISSUE TITLE
Could not perpetuate Job Scheduler Process

### ISSUE THREAD

**Issue by calebkortuem** [zachelrath/Relax#15]
I received an error which stated:
Message: Based on configured schedule, the given trigger will never fire.
Line Number: 121
Stack Trace:(relax)

Since all of my schedules are set to "Run Individually" they're all still processing but the Last Run Date is not being updated on the View in Salesforce.  Any way I can manually restart the JobScheduler?

**Comment by zachelrath** [comment]
You can restart the scheduler by deactivating one or more of the jobs, saving, then re-activating.

**Comment by calebkortuem** [comment]
Perfect.  Thank you for the quick response!
