### ISSUE TITLE
Ability to Include a Parameter (enhancement)

### ISSUE THREAD

**Issue by zjeh** [zachelrath/Relax#5]
Hi Zach,

A nice enhancement would be having ability to include a parameter with the scheduling. Have you given this any thought?

I am thinking a single string that will be passed in the Apex call. I have seen some batch classes where all or part of the query to use is passed in.

**Comment by zachelrath** [comment]
Hi zjeh, 

Are you referring to the ability to set some instance variables, or to have custom constructors, for Batch Apex or Scheduled Apex classes? If so, that is an excellent idea, well worth considering. To do this for Scheduled Classes, I would have to do a custom "Schedulable" interface that extends the `System.Schedulable` interface, but that's doable, as I'm already doing that for Batch Apex classes with the `BatchableProcessStep` interface. 

My initial idea would be to expect a Map<String,Object> of params, which could be deserialized from a JSON representation which would be stored in a Long Text field on the `Job__c` object called `Parameters__c`. So for instance you could have `Parameters__c` be (excuse my unescaped JSON): "{"foo":"bar","contactId":"003000000023338c"}"

So then when the class is loaded, all of these Parameters would be loaded in to a "parameters" variable which would be accessible to your implementation class, achieving exactly what would be accomplished by setting instance variables and/or having a custom constructor. Great idea!

This is especially helpful to consider now as Interfaces (such as `BatchableProcessStep`) cannot be modified once they're made Global, which I'll have to do prior to releasing Relax as a Managed Package.

Let me know what you think about this proposal.

Zach

**Comment by zjeh** [comment]
Yes, you got it perfectly. I was thinking custom constructors for Batch Apex, and I think you nailed it with using a Map and JSON. That solves the next step I hadn't figured out a good approach for yet - passing a list to use with WHERE IN clause. A great idea and much more flexibility.

**Comment by zachelrath** [comment]
Cool. I'll probably implement it through a 'load()' or 'configure()' method on the interface which will be called if there is content in the Parameters field.

**Comment by zachelrath** [comment]
Added in v1.1.
