### ISSUE TITLE
Unit Tests failing in beta 5

### ISSUE THREAD

**Issue by zjeh** [zachelrath/Relax#8]
BatchAccountsUpdater class is used in unit tests, but is not included in beta 5 managed package.
"System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, 'relax.BatchAccountsUpdater' is not a valid Apex Class."

![image](https://f.cloud.github.com/assets/2139356/911943/d5b77f2e-fdf6-11e2-8ab4-f07234e418ea.png)

**Comment by zachelrath** [comment]
Thanks for reporting this! This will be resolved in the next release. 

Btw, I'm planning to make a Managed-Released version of the app in the next few days, and will be doing a session on Dreamforce about Relax, so if you have any other ideas for enhancements, let me know.

**Comment by zachelrath** [comment]
This has been resolved in release 1.1, now available.
